# Generated by Django 2.1.1 on 2020-05-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rmsgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgR', models.TextField(max_length=1900)),
                ('datek', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('sender', models.CharField(default='rand', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SheSouldKnow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgR', models.TextField(max_length=1900)),
                ('datek', models.DateTimeField(auto_now_add=True)),
                ('sender', models.CharField(default='rand', max_length=200)),
            ],
        ),
    ]
