# Generated by Django 2.1.1 on 2020-05-12 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rand', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shesouldknow',
            old_name='msgR',
            new_name='msgr',
        ),
    ]
