# Generated by Django 2.1.1 on 2020-05-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rand', '0003_auto_20200513_0420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rmsgs',
        ),
        migrations.DeleteModel(
            name='SheSouldKnow',
        ),
    ]
