# Generated by Django 2.1.1 on 2020-04-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kmsgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgK', models.TextField(max_length=1900)),
                ('datek', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
