# Generated by Django 2.1.1 on 2020-04-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnooz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmsgs',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
