# Generated by Django 2.1.1 on 2020-04-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qnooz', '0002_kmsgs_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmsgs',
            name='sender',
            field=models.CharField(default='Knooz', max_length=200),
        ),
    ]
